# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6425f0552182ca54ad850f5a1b990eb8f8ceb57e250a3b7bba68dcf62cced551db43e9c02df9042ff1c2ef64370776d13092130928154a07fd633e85334b0ef1

test:
  secret_key_base: 8222a3802cc829fba80c6604cfa05917c90608085798757ac6d5b96daaf7357cad627a21d454ee104d06a42b2899e53fa824781ef49c2a15e57fcc51ee0dbc73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
